# Generated by Django 3.1 on 2023-08-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_variationmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='product',
            new_name='Product',
        ),
    ]
