# Generated by Django 3.1 on 2023-08-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230802_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
