# Generated by Django 3.1 on 2023-08-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_variationmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Product',
            new_name='product',
        ),
    ]
