# Generated by Django 3.1 on 2023-07-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20230729_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Cart_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
