# Generated by Django 3.1 on 2023-08-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
    ]
