# Generated by Django 3.1 on 2023-08-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20230803_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(default='default_color', max_length=50),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='default_size', max_length=50),
        ),
    ]
