# Generated by Django 3.1 on 2023-08-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
