# Generated by Django 3.1 on 2023-08-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_user',
        ),
    ]
