# Generated by Django 4.2.4 on 2023-08-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_amount_paid_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
