# Generated by Django 4.2.4 on 2023-08-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
