# Generated by Django 4.2.4 on 2023-08-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_poduct_price_orderproduct_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creeted_at',
            new_name='created_at',
        ),
    ]
