# Generated by Django 4.2.4 on 2023-08-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_creeted_at_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(default='New', max_length=200, unique=True),
        ),
    ]
