# Generated by Django 4.2.4 on 2023-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
